export type ItemComicProps = {
    author: string,
    category: any,
    chapter_update: string,
    chapter_update_count: number,
    commentCount: number,
    createdAt: string,
    description: string,
    devices: any,
    enable: true,
    first_chapter: string,
    image: string,
    last_chapter: string,
    manga_status: number,
    name: string,
    updatedAt: string,
    url: string,
    views: number,
    __v: number,
    _id: string,
}